--Puestos con lista de categorias

select PUESTO.ID_PUESTO, NOMBRE_PUESTO, SALARIO, LINK_IMAGEN,
       LISTAGG(C2.NOMBRE_CATEGORIA, ',') within group ( order by C2.NOMBRE_CATEGORIA) as Categorias,
       PD.ID_DEPARTAMENTO
from PUESTO
INNER JOIN PUESTO_CATEGORIA PC on PUESTO.ID_PUESTO = PC.ID_PUESTO
INNER JOIN CATEGORIA C2 on PC.ID_CATEGORIA = C2.ID_CATEGORIA
INNER JOIN PUESTO_DEPARTAMENTO PD on PUESTO.ID_PUESTO = PD.ID_PUESTO
group by PUESTO.ID_PUESTO, NOMBRE_PUESTO, SALARIO, LINK_IMAGEN, PD.ID_DEPARTAMENTO
;

--Lista de Usuarios
select ID_USUARIO,  USERNAME, PASSWORD, R.NOMBRE_ROL, D.NOMBRE_DEPARTAMENTO, to_char(FECHA_INI,'DD/MM/YYYY')
from USUARIO
inner join DEPARTAMENTO D on D.ID_DEPARTAMENTO = USUARIO.ID_DEPARTAMENTO
inner join ROL R on R.ID_ROL = USUARIO.ID_ROL
where ESTADO = 1;


--Lista de departamentos especialmente para el coordinador
select * from DEPARTAMENTO Dep WHERE not Exists(
    select * from(
                  select Dep.ID_DEPARTAMENTO, Dep.NOMBRE_DEPARTAMENTO
FROM DEPARTAMENTO Dep
inner join USUARIO on Dep.ID_DEPARTAMENTO = USUARIO.ID_DEPARTAMENTO
inner join ROL on USUARIO.ID_ROL = ROL.ID_ROL
where rol.ID_ROL = 2
)Coors
where Dep.ID_DEPARTAMENTO = Coors.ID_DEPARTAMENTO);


--Lista de revisores disponibles
select REVISOR_EXPEDIENTES.ID_REVISOR_EXPEDIENTES
    from REVISOR_EXPEDIENTES
    inner join USUARIO on REVISOR_EXPEDIENTES.ID_USUARIO = USUARIO.ID_USUARIO
    group by CANTIDAD_EXP, USUARIO.ID_DEPARTAMENTO, USUARIO.ESTADO, ID_REVISOR_EXPEDIENTES
having USUARIO.ID_DEPARTAMENTO = 1
and USUARIO.ESTADO = 1
ORDER BY CANTIDAD_EXP ASC
fetch next 1 rows only
;

--Lista de expedientes por Revisor
select E.DPI, E.NOMBRES, E.APELLIDOS, E.EMAIL, E.DIRECCION, E.TELEFONO,
       to_char(E.FECHA_POST,'DD/MM/YYYY') FECHA, P.NOMBRE_PUESTO, E.CV, E.ID_EXPEDIENTE, U.ID_DEPARTAMENTO
from EXPEDIENTE E
inner join PUESTO P on P.ID_PUESTO = E.ID_PUESTO
inner join REVISOR_EXPEDIENTES RE on RE.ID_REVISOR_EXPEDIENTES = E.ID_REV_EXP
inner join USUARIO U on RE.ID_USUARIO = U.ID_USUARIO
where E.REVISADO = 0
and RE.ID_USUARIO = 2
;



select * from USUARIO;
select * from REVISOR_EXPEDIENTES;
select * from EXPEDIENTE




commit;