

CREATE OR REPLACE PROCEDURE RelacionarRevisor(P_DPI IN NUMBER, P_NOMBRES IN VARCHAR,
                                              P_APELLIDOS IN VARCHAR,
                                              P_EMAIL IN VARCHAR, P_DIRECCION IN VARCHAR,
                                              P_TELEFONO IN NUMBER, P_CV IN VARCHAR,
                                              P_FECHA IN VARCHAR, P_ID_PUESTO IN NUMBER,
                                              P_ID_DEPARTAMENTO IN NUMBER)
IS
    revisor NUMBER;
BEGIN
    select REVISOR_EXPEDIENTES.ID_REVISOR_EXPEDIENTES into revisor
    from REVISOR_EXPEDIENTES
    inner join USUARIO on REVISOR_EXPEDIENTES.ID_USUARIO = USUARIO.ID_USUARIO
    group by CANTIDAD_EXP, USUARIO.ID_DEPARTAMENTO, USUARIO.ESTADO, ID_REVISOR_EXPEDIENTES, P_ID_DEPARTAMENTO
    having USUARIO.ID_DEPARTAMENTO = P_ID_DEPARTAMENTO
    and USUARIO.ESTADO = 1
    ORDER BY CANTIDAD_EXP ASC
    fetch next 1 rows only
    ;

    insert into EXPEDIENTE (DPI, NOMBRES, APELLIDOS, EMAIL, DIRECCION, TELEFONO, CV, REVISADO, CORREGIR,
                        FECHA_POST, ID_PUESTO, ID_REV_EXP)
    values (P_DPI, P_NOMBRES, P_APELLIDOS, P_EMAIL, P_DIRECCION, P_TELEFONO, P_CV, 0, 2,
            TO_DATE(P_FECHA, 'DD/MM/YYYY'), P_ID_PUESTO, revisor);

    update REVISOR_EXPEDIENTES
    set CANTIDAD_EXP = CANTIDAD_EXP + 1
    where ID_REVISOR_EXPEDIENTES = revisor;

END RelacionarRevisor;




CREATE OR REPLACE PROCEDURE RechazarExp(E_EXP IN NUMBER, E_REVISOR_EXP IN NUMBER)
IS
BEGIN
    update EXPEDIENTE
    set REVISADO = 2
    where ID_EXPEDIENTE = E_EXP;


    update REVISOR_EXPEDIENTES
    set CANTIDAD_EXP = CANTIDAD_EXP - 1
    where ID_REVISOR_EXPEDIENTES = E_REVISOR_EXP;

END RechazarExp;


CREATE OR REPLACE PROCEDURE AceptarExp(E_EXP IN NUMBER, E_REVISOR_EXP IN NUMBER, U_DPI in VARCHAR,
                                       U_PASSWORD IN VARCHAR, U_FECHA IN VARCHAR, U_DEP IN NUMBER)
IS
    usuarioN NUMBER;
BEGIN

    update EXPEDIENTE
    set REVISADO = 1
    where ID_EXPEDIENTE = E_EXP;


    update REVISOR_EXPEDIENTES
    set CANTIDAD_EXP = CANTIDAD_EXP - 1
    where ID_REVISOR_EXPEDIENTES = E_REVISOR_EXP;

    insert into USUARIO (USERNAME, PASSWORD, FECHA_INI, ESTADO, ID_ROL, ID_DEPARTAMENTO)
    values (U_DPI, U_PASSWORD, TO_DATE(U_FECHA, 'DD/MM/YYYY'), 1, 4, U_DEP);

    select USUARIO.ID_USUARIO into usuarioN
    from USUARIO
    where USUARIO.USERNAME = U_DPI
    and USUARIO.PASSWORD = U_DPI;

    update EXPEDIENTE
    set EXPEDIENTE.ID_USUARIO = usuarioN
    where EXPEDIENTE.ID_EXPEDIENTE = E_EXP;
END AceptarExp;

